# Generated by Django 5.1 on 2026-05-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
    ]
