# Generated by Django 5.1 on 2026-05-17 11:52

import django.db.models.deletion
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('conditions', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Datetime'), ('email', 'Email'), ('url', 'URL'), ('dropdown', 'Dropdown'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('rating', 'Rating')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=None, null=True)),
                ('validation_rules', models.JSONField(blank=True, default=None, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('maps_to', models.CharField(blank=True, choices=[('respondent_full_name', 'Respondent Full Name'), ('respondent_email', 'Respondent Email'), ('respondent_phone', 'Respondent Phone')], max_length=50, null=True)),
                ('conditions', models.JSONField(blank=True, default=None, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='surveys_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys_app.survey'),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys_app.respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys_app.survey')),
            ],
        ),
        migrations.CreateModel(
            name='FieldResponse',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys_app.field')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='surveys_app.surveyresponse')),
            ],
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['section'], name='surveys_app_section_402a62_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['order'], name='surveys_app_order_d4d48c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('section', 'order')},
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status'], name='surveys_app_status_e4814a_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_by'], name='surveys_app_created_715335_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['-created_at'], name='surveys_app_created_c6fcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['survey'], name='surveys_app_survey__9ffc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['order'], name='surveys_app_order_e97869_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('survey', 'order')},
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey'], name='surveys_app_survey__7c3646_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['respondent'], name='surveys_app_respond_d6c894_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['status'], name='surveys_app_status_0eb080_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('survey', 'respondent')},
        ),
        migrations.AddIndex(
            model_name='fieldresponse',
            index=models.Index(fields=['survey_response', 'field'], name='surveys_app_survey__804ec9_idx'),
        ),
    ]
